FROM messense/rust-musl-cross:aarch64-musl AS build

WORKDIR /src
COPY . /src

RUN cargo build --release --target aarch64-unknown-linux-musl

FROM --platform=linux/arm64/v8 alpine:latest

LABEL org.opencontainers.image.source=https://github.com/wadedesirco/test-project

COPY --from=build /src/target/aarch64-unknown-linux-musl/release/test-project /usr/bin/

ENTRYPOINT [ "test-project" ]
